name: "Deploy"
on:
  push:
    branches:
      - master
    tags:
    - '*'
jobs:
  deploy-to-githubio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: npm install
      run: npm install
    - name: compile typescript
      run: "npm run build"
    - name: Create directory 'public'
      run: mkdir ./public && mkdir ./public/scripts
    - name: Move data to 'public'
      run: |- 
        mv ./scripts/*.js ./public/scripts
        mv ./fonts ./public
        mv ./styles ./public
        mv ./images ./public
        mv index.html ./public
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public